# Generated by Django 3.1 on 2021-05-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0007_statusupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusUpdate',
        ),
    ]
